import type { Metadata } from "next";
import Link from "next/link";
import { PublicFooter, PublicNav } from "@/components/shell/public-nav";
import { Kick } from "@/components/ui/primitives";
import { SITE, absoluteUrl } from "@/lib/site";

export const metadata: Metadata = {
  title: "Terms & Conditions",
  description: "The terms for using FestFlow as a student or as a college running a fest: accounts, registrations, tickets, certificates, acceptable use and liability.",
  alternates: { canonical: absoluteUrl("/terms") },
};

export default function TermsPage() {
  return (
    <div className="flex min-h-dvh flex-col">
      <PublicNav />
      <main id="main" className="mx-auto w-full max-w-[720px] flex-1 px-[18px] pb-16 pt-8 sm:px-6 sm:pt-14">
        <Kick className="mb-2">Effective {SITE.legalUpdated}</Kick>
        <h1 className="mb-3 text-[32px] font-medium leading-[1.05] tracking-[-0.03em] sm:text-[40px]">Terms &amp; Conditions</h1>
        <p className="mb-9 max-w-[56ch] text-[15px] text-neutral-300">
          These terms are an agreement between you and Plansphere, the operator of FestFlow at plansphere.in (“the service”). By creating an account or
          using the service you accept them. If you are using FestFlow on behalf of a college or organisation, you confirm you are authorised to bind it.
        </p>

        <Section title="1. The service">
          <p>
            FestFlow lets colleges publish fests and events, take registrations, admit participants with a QR pass, count meals, publish results and
            issue verifiable certificates; and lets students find fests, register alone or as a team, hold their passes and collect their certificates.
            FestFlow is the platform. Each fest is run by the college that publishes it (“the organizer”), which decides its events, fees, capacity,
            eligibility, rules and results.
          </p>
        </Section>

        <Section title="2. Accounts">
          <p>
            You must give accurate details and keep your email address working — passes, invitations and certificates are sent to it. You are
            responsible for activity under your account. Staff accounts (organizer, admin) are created only by invitation from a super admin and are
            scoped to the fests they manage. Do not share a staff account. We may suspend an account that breaks these terms or threatens the service.
          </p>
        </Section>

        <Section title="3. Registrations, teams and tickets">
          <p>
            A registration holds a seat only when the service confirms it; where an event is full and a waitlist is on, you are told you are waitlisted
            and moved up automatically if a seat opens. When you add teammates you confirm you may share their name and email with us and the
            organizer; they are invited and may decline, which releases their seat. The QR pass is personal to the entry; one pass admits the members
            listed on it and is used at the gate exactly once. Do not resell, forge or alter a pass. You may cancel an entry until the event starts;
            after that the record stands.
          </p>
        </Section>

        <Section title="4. Fees and refunds">
          <p>
            Where an event has an entry fee it is set and collected by the organizer, and the organizer’s refund policy applies. FestFlow does not hold
            your money. If an organizer cancels an event, refunds are between you and the organizer; we will help you reach them.
          </p>
        </Section>

        <Section title="5. Results and certificates">
          <p>
            Results are published by the organizer and may be amended by them. Certificates are generated by the service only after attendance is
            confirmed and, for awards, after results are published; a participant cannot issue their own. Each certificate carries a number and a
            public verification page. An organizer may revoke a certificate issued in error; the verification page then says so rather than hiding it.
          </p>
        </Section>

        <Section title="6. Organizers’ responsibilities">
          <p>
            If you run a fest on FestFlow you are responsible for the accuracy of what you publish, for handling participants’ data lawfully and only
            for the fest, for your own refund and conduct policies, and for the actions of the staff and volunteers you add. Every privileged action on
            the platform is recorded in an audit log against the account that took it.
          </p>
        </Section>

        <Section title="7. Acceptable use">
          <p>
            Do not attempt to access data that is not yours, probe or overload the service, scrape participants’ details, create accounts
            automatically, upload malware or unlawful content, impersonate anyone, or use the service to harass. We rate-limit public endpoints and
            block abusive traffic, and we may report serious misuse.
          </p>
        </Section>

        <Section title="8. Content and intellectual property">
          <p>
            You keep the rights to what you upload (posters, banners, result sheets) and grant us a licence to store, display and deliver it as part of
            the service. The FestFlow software, design and name belong to Plansphere. Certificates are documents of the issuing organizer, generated by
            the service.
          </p>
        </Section>

        <Section title="9. Availability and changes">
          <p>
            We aim to keep the service available around fest days and to give notice of planned maintenance, but we do not guarantee uninterrupted
            access. The gate scanner and passes are designed to keep working without a network connection. We may change or discontinue features; we
            will not remove your access to certificates already issued without giving you a way to keep them.
          </p>
        </Section>

        <Section title="10. Liability">
          <p>
            The service is provided “as is”. To the extent the law allows, Plansphere is not liable for indirect or consequential loss, for an
            organizer’s decisions about its fest (eligibility, results, refunds, cancellations), or for loss caused by inaccurate information you or an
            organizer entered. Nothing here limits liability that cannot be limited by law. Where liability is not excluded, our total liability to you
            is limited to the fees you paid us in the twelve months before the claim, which for students is nil.
          </p>
        </Section>

        <Section title="11. Privacy">
          <p>
            How we handle personal data is described in the <Link href="/privacy">Privacy Policy</Link>, which forms part of these terms.
          </p>
        </Section>

        <Section title="12. Governing law and contact">
          <p>
            These terms are governed by the laws of India, and the courts of Kolkata, West Bengal have jurisdiction. Questions about these terms go to{" "}
            <a href={`mailto:${SITE.contact.hello}`}>{SITE.contact.hello}</a>. When the terms change we update the date at the top; continued use after a
            change is acceptance of it.
          </p>
        </Section>
      </main>
      <PublicFooter />
    </div>
  );
}

const Section = ({ title, children }: { title: string; children: React.ReactNode }) => (
  <section className="mb-9">
    <h2 className="mb-3 text-[18px] font-medium tracking-[-0.01em]">{title}</h2>
    <div className="flex flex-col gap-3 text-[14px] leading-relaxed text-neutral-300 [&_p]:max-w-[60ch]">{children}</div>
  </section>
);
